FROM node:18-bullseye

WORKDIR /app

COPY wsu-hw-ng-main/ ./wsu-hw-ng-main

WORKDIR /app/wsu-hw-ng-main

RUN npm install -g @angular/cli \
    && npm install \
    && ng build --configuration production \
    && npm install -g http-server

CMD ["http-server", "dist/wsu-hw-ng-main", "-p", "4200"]
